language: node_js
dist: trusty
sudo: false
install:
  - npm install --production
script:
  - npm run travis
node_js:
  - stable
env:
  - RESPONSE_TYPE=code
  - RESPONSE_TYPE=id_token
  - RESPONSE_TYPE=id_token+token
  - RESPONSE_TYPE=code+id_token
  - RESPONSE_TYPE=code+id_token+token
  - RESPONSE_TYPE=code+token
